### ISSUE TITLE
Write debug steps for docker failing to compile.

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#141]
1. Did you restart the godot editor once
2. Is dlls unblocked on windows
3. ??? Investigate docker images being out of date
4. Check the sandbox scripts manually and change a space to force recompile
5. The godot-sandbox dlls is behind the docker version

**Comment by fwsGonzo** [comment]
It used to be that when you changed Godot project, the already-started container wouldn't be pointed towards the new project, and it would just fail to compile .cpp files in the new project. But I fixed that by inspecting the path of the mounted volume on startup. So, unless something is wrong, the compilation step should Just Work now, even if the project changes.

It's also possible to build the project with verbose docker enabled, using the CMake project in the root. So, just build it locally on your machine and enable more verbose (or add verbose-ness as needed), and let me know where the issue was?

**Comment by fwsGonzo** [comment]
The Docker image can indeed be out of date. The running container needs to be shut down, removed (deleted), and only then can you let the pull and start a new one. I'm not sure what the right thing to do here is, since messing with peoples systems is not good engineering. It's just better if people can figure out basic container management on their own.

**Comment by fire** [comment]
For me, the implementation of native compilation makes this not a problem.
