### ISSUE TITLE
Out of words

### ISSUE THREAD

**Issue by CycloneRing** [libriscv/godot-sandbox#62]
This project is simply amazing! I don't know what to say, This is insane and the fact you adopted this to Godot and used it for Gamedev, I am simply out of words to express how impressed I am, The source code is very clean and neat, This is top development at its best, Thank you so much and I will going to use this project on our upcoming indie game.

Just amazing...

**Comment by fwsGonzo** [comment]
Thank you. I hope you will find it useful, and if there's anything just post an issue. I want to mention that the project isn't mature enough to be vetted, so that the sandboxing guarantee isn't fully in place yet. It's somewhat about understanding which parts of Godot are dangerous and which are not.

**Comment by fwsGonzo** [comment]
I'll close this as it's not actionable, but thanks for the encouraging words :)
