### ISSUE TITLE
Enable binary translator

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#98]
Pending work

**Comment by fwsGonzo** [comment]
It's really just a switch, but the fancy binary translations only make sense for two things:
- Dynamic languages where we build a custom ELF that doesn't change often, which is then fed text that is dynamically compiled, like a LuaJit program
- Final shipped binaries, like just before you ship your game you can start making final builds - including for Nintendo Switch and other obscure platforms. Final-build binary translation is just C code that you embed *somewhere* (anywhere, really).

Otherwise, there's the libtcc-jit that I've only made use of on Linux. I can attest to it working with Godot sandbox. We could automatically build .dll's for other platforms, like Windows, but I'm worried about the unblocking-thing.

**Comment by fire** [comment]
Godot Engine architecture has assets imported for the final build at import time.

The export time is a file copy to the various platforms.

**Comment by fwsGonzo** [comment]
With https://github.com/libriscv/godot-sandbox/pull/168 the binary translations now work on all platforms, including Web export
